### ISSUE TITLE
icons of shortcuts on dashboard should use the main color of theme 

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#164]
![dashboard___comunique-se](https://cloud.githubusercontent.com/assets/9011612/8716398/1118a5ee-2b67-11e5-8c15-49b6a5b5bb72.png)

**Comment by t4deu** [comment]
This was caused because the segment custom css isn't overwriting the default style.

The segment sass template need to be updated, to prevent this error when a new segment is created:
sitebuilder/assets/styles/segment.scss
```css
...                                                 
.featured-list li .link .icons {                                                           
  color: $main-color;                                                               
}  
```
Add the selector on the custom styles of segments to fix the issue on segments that already exist:
line 120, segments/{segment}/public/styles/segment.css 
```css
.featured-list li .link h3,                                                         
.featured-list  li .link .icons, 
.featured-list li:hover .arrow,                   
div.dashboard .domain a {                                                           
  color: #2f3e6e; 
} 
```
